name: mafahim_app
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: '>=3.4.0 <4.0.0'

assets: 
  - assets/img/

dependencies:
  cupertino_icons: ^1.0.6
  flutter:
    sdk: flutter
  flutter_easyloading: ^3.0.5
  flutter_native_splash: ^2.4.0
  get: 4.6.6
  sp_util: ^2.0.3

dev_dependencies:
  flutter_lints: 4.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
